version: '3'

services:
  mlt-maker:
    image: mlt-maker
    # runtime: nvidia
    # devices:
    #   - /dev/nvidia0:/dev/nvidia0
    volumes:
      - ./voices:/voices
      - ./csv:/csv
    environment:
      - TARGET_VOICE_DIR=PEARL
      - MODEL_NAME=PEARL