version: '3'

services:
  vad-test:
    image: vad-test
    volumes:
      - ./voices:/voices
      - ./csv:/csv
    environment:
      - PYTHONUNBUFFERED=1
      - VOICES_DIR=/CHIM
      - MODEL_NAME=CHIM