version: '3.8'

services:
  mlt-maker:
    image: mlt-maker
    runtime: nvidia
    deploy:
      resources:
        limits:
          memory: '8G'
    command: python3 /src/vad.py
    devices:
      - /dev/nvidia0:/dev/nvidia0
    volumes:
      - ./voices/CHIM:/voices/CHIM
      - ./output:/output
      - ./src:/src
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - TARGET_VOICE_DIR=CHIM
      - MODEL_NAME=CHIM_test
      - MIN_VOICE_LENGTH=3.0
      - MAX_VOICE_LENGTH=10.0