version: '3.8'

services:
  mlt-maker:
    image: mlt-maker
    runtime: nvidia
    deploy:
      resources:
        limits:
          # cpus: '0.5'
          memory: '8G'
    devices:
      - /dev/nvidia0:/dev/nvidia0
    volumes:
      - ./voices/CHIM:/voices/CHIM
      - ./csv:/csv
      - ./src:/src
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - TARGET_VOICE_DIR=CHIM
      - MODEL_NAME=CHIM
      - MIN_VOICE_LENGTH=3.0
      - MAX_VOICE_LENGTH=20.0